### ISSUE TITLE
Establish Prototype Candidate

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#15]
Decide which teammates final project for the previous class we want to use.

**Comment by vla5qpb7** [comment]
I assume this issue is about this from https://uvu.instructure.com/courses/546771/pages/spr-1-document?module_item_id=10056533:
> Select one or two candidates for the prototype from CS 1410 – Files are also in the course Project Files folder.

payroll.py is the only CS 1410 project I could find in the course files. Should we go with that, or do one of you guys have a different project you think we should use? I'm thinking we should do the simplest one we can.

**Comment by ZachYlst** [comment]
I'm fairly certain the payroll.py project is what he was referring to. I still have mine, so if you guys want I can add the file to our repository.

**Comment by vla5qpb7** [comment]
What would you think about doing a quick comparison of yours and the other one provided to see which one seems easier to work with?

**Comment by ZachYlst** [comment]
Ok, I just looked over both and I personally think that mine is a bit cleaner, so I'd say we go with it. I also double checked to make sure it still worked, and it seems to work just fine.
