### ISSUE TITLE
Requirements spec draft ready to review with stakeholder

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#23]
"Team and product requirements specs reviewed with Shareholder and completed for work to date." - Rubric

**Comment by vla5qpb7** [comment]
Just finished a first draft of this document in our shared Drive.

**Comment by david3214** [comment]
update on requirements spec. This is the Professors definition of a Spec: Statement of the requirement, and the steps needed to implement it
`Example` of requirement spec for login screen method.
Design of login screen method example in English
Must gather correct name provided by Admin in Emp database
Must send out message that employee not yet enrolled
Must send out login error if incorrect
Must appear when selecting entry login button or automatically appear
Must verify by login name and password
Set user permissions and adjust GUI*
This design depends upon GUI`

**Comment by JoshuaJKrueger** [comment]
"Requirements spec is complete and follows the chapter 4 slides for requirements characteristics." - Rubric
Based on the chapter 4 slides and chapter 4 in the text book I feel that our requirements are fine, however since the professor wants the requirement and implementation steps it is much closer to a full high level design. I think we might want to discuss the full design more as a team (because I at least don't have a clear picture of the whole employee payroll management system that we are going to be building yet) before we leave this assigned to one person, or even just put it together as a team. I think it will require reworking our current requirements document a little as well as adding all the implementations steps, which seems like a lot to put on one person.

Side note:
In the example from the sprint 6 document they broke down the entire application to which screens they would have and listed how they would implement those steps. While I don't think that is the best method it seems like a good way to start

**Comment by vla5qpb7** [comment]
I assume I should reopen this and issue and revise the document.
